#!/usr/bin/env python3
"""Write geosite rules a domain rule-set cannot hold into a classical YAML."""

from __future__ import annotations

import argparse
from pathlib import Path

HEADER = """# Generated by scripts/build-reject-all.sh -- do not edit by hand.
#
# Upstream geosite entries that a Mihomo domain rule-set cannot express.
# Keyword and regex rules have no representation in a domain MRS, so they live
# here as a classical rule-set instead of being dropped.
"""


def quote(rule: str) -> str:
    return "'" + rule.replace("'", "''") + "'"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("inputs", nargs="+", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    rules = sorted(
        {
            line.strip()
            for path in args.inputs
            for line in path.read_text(encoding="utf-8").splitlines()
            if line.strip()
        }
    )
    body = "".join(f"  - {quote(rule)}\n" for rule in rules)
    args.output.write_text(f"{HEADER}payload:\n{body}", encoding="utf-8")
    print(len(rules))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
